/**
 * Barrel export for all protocol types and Zod schemas.
 */

// Base protocol
export {
  BaseMessageSchema,
  type BaseMessage,
  type EngineEvent,
  type TuiAction,
  ENGINE_EVENT_TYPES,
  TUI_ACTION_TYPES,
  type EngineEventType,
  type TuiActionType,
  ConnectionState,
  type ConnectionState as ConnectionStateType,
  messageSchema,
} from './protocol.js';

// Shared types
export {
  // Agent
  AgentTypeSchema,
  type AgentType,
  AgentStatusSchema,
  type AgentStatus,

  // Diff
  DiffLineSchema,
  type DiffLine,
  DiffHunkSchema,
  type DiffHunk,
  DiffInfoSchema,
  type DiffInfo,

  // Knowledge base
  KbChunkResultSchema,
  type KbChunkResult,
  SubQuestionResultSchema,
  type SubQuestionResult,

  // Sidebar data
  AgentInfoSchema,
  type AgentInfo,
  FileActionSchema,
  type FileAction,
  FileInfoSchema,
  type FileInfo,
  PlanInfoSchema,
  type PlanInfo,
  ActionCategorySchema,
  type ActionCategory,
  RoutingEntrySchema,
  type RoutingEntry,
  RoutingTableSchema,
  type RoutingTable,
  ActivityInfoSchema,
  type ActivityInfo,

  // Status
  AgentPhaseSchema,
  type AgentPhase,
  PermissionModeSchema,
  type PermissionMode,
  SystemLevelSchema,
  type SystemLevel,

  // Engine -> TUI events
  StreamDeltaSchema,
  type StreamDelta,
  StreamEndSchema,
  type StreamEnd,
  ToolCallStartSchema,
  type ToolCallStart,
  ToolCallUpdateSchema,
  type ToolCallUpdate,
  ToolCallCompleteSchema,
  type ToolCallComplete,
  PermissionRequestSchema,
  type PermissionRequest,
  AskUserRequestSchema,
  type AskUserRequest,
  StatusUpdateSchema,
  type StatusUpdate,
  AgentSpawnedSchema,
  type AgentSpawned,
  AgentStatusChangedSchema,
  type AgentStatusChanged,
  AgentCompletedSchema,
  type AgentCompleted,
  AgentFailedSchema,
  type AgentFailed,
  UsageUpdateSchema,
  type UsageUpdate,
  KbResultSchema,
  type KbResult,
  SystemMessageSchema,
  type SystemMessage,
  BannerSchema,
  type Banner,
  SidebarUpdateSchema,
  type SidebarUpdate,
  ModelInfoSchema,
  type ModelInfo,
  ContextFilesUpdateSchema,
  type ContextFilesUpdate,
  EngineEventSchema,
  type EngineEvent as EngineEventUnion,

  // TUI -> Engine actions
  SubmitPromptSchema,
  type SubmitPrompt,
  RunInBackgroundSchema,
  type RunInBackground,
  CancelAgentSchema,
  type CancelAgent,
  ResolvePermissionSchema,
  type ResolvePermission,
  ResolveAskUserSchema,
  type ResolveAskUser,
  KbFeedbackSchema,
  type KbFeedback,
  ChangePermissionModeSchema,
  type ChangePermissionMode,
  ToggleContextFileSchema,
  type ToggleContextFile,
  ChangeRoutingSchema,
  type ChangeRouting,
  ClearChatSchema,
  type ClearChat,
  SlashCommandSchema,
  type SlashCommand,
  UpdateModelSchema,
  type UpdateModel,
  MoeDispatchSchema,
  type MoeDispatch,
  InjectSkillSchema,
  type InjectSkill,
  QuitSchema,
  type Quit,
  TuiActionSchema,
  type TuiAction as TuiActionUnion,

  // Combined
  AnyMessageSchema,
  type AnyMessage,
} from './messages.js';

// Chat message types (rendered messages for the chat panel)
export {
  type ChatMessage,
  type UserChatMessage,
  type AssistantChatMessage,
  type SystemChatMessage,
  type ToolCallChatMessage,
  type KBResultChatMessage,
  type BannerChatMessage,
  nextMessageId,
} from './chat.js';
